name: Compile ESP-IDF Sketches for v5.1

on:
  pull_request:
    paths:
      - ".github/workflows/espidf-compile-*.yml"
      - "main/**"
      - "components/**"
      - "CMakeLists.txt"
      - "Kconfig"
      - "partitions.csv"
      - "sdkconfig.defaults"

  push:
    paths:
      - ".github/workflows/espidf-compile-*.yml"
      - "main/**"
      - "components/**"
      - "CMakeLists.txt"
      - "Kconfig"
      - "partitions.csv"
      - "sdkconfig.defaults"
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        idf_ver:
          - release-v5.0
          - release-v5.1
        idf_target:
          - esp32
          - esp32s3
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Build Application with ESP-IDF
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: ${{ matrix.idf_ver }}
        target: ${{ matrix.idf_target }}
        path: '.'